// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A personalized insights AI agent.
 *
 * - getPersonalizedInsights - A function that handles the personalized insights process.
 * - PersonalizedInsightsInput - The input type for the getPersonalizedInsights function.
 * - PersonalizedInsightsOutput - The return type for the getPersonalizedInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const PersonalizedInsightsInputSchema = z.object({
  habits: z.array(
    z.object({
      name: z.string().describe('The name of the habit.'),
      isNegative: z.boolean().describe('Whether the habit is negative or not.'),
      activities: z.array(
        z.object({
          date: z.string().describe('The date of the activity (YYYY-MM-DD).'),
          count: z.number().describe('The number of activities for the habit on this day.'),
          comment: z.string().optional().describe('Optional comment for the activity.'),
        })
      ),
      streak: z.number().describe('The current streak for the habit.'),
    })
  ).describe('An array of habit data for the user.'),
});
export type PersonalizedInsightsInput = z.infer<typeof PersonalizedInsightsInputSchema>;

const PersonalizedInsightsOutputSchema = z.object({
  insights: z.array(
    z.object({
      habitName: z.string().describe('The name of the habit the insight is for.'),
      insight: z.string().describe('The personalized insight for the habit.'),
      suggestion: z.string().describe('A suggestion based on the insight.'),
    })
  ).describe('An array of personalized insights and suggestions.'),
});
export type PersonalizedInsightsOutput = z.infer<typeof PersonalizedInsightsOutputSchema>;

export async function getPersonalizedInsights(input: PersonalizedInsightsInput): Promise<PersonalizedInsightsOutput> {
  return personalizedInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'personalizedInsightsPrompt',
  input: {schema: PersonalizedInsightsInputSchema},
  output: {schema: PersonalizedInsightsOutputSchema},
  prompt: `You are an AI assistant that analyzes user habit tracking data and provides personalized insights and suggestions.

  Analyze the following habit data and provide insights and suggestions for each habit.

  Habit Data:
  {{#each habits}}
  Habit Name: {{name}}
  Is Negative: {{isNegative}}
  Activities:
  {{#each activities}}
  Date: {{date}}, Count: {{count}}, Comment: {{comment}}
  {{/each}}
  Streak: {{streak}}
  {{/each}}

  Provide your output in JSON format.
  `,
});

const personalizedInsightsFlow = ai.defineFlow(
  {
    name: 'personalizedInsightsFlow',
    inputSchema: PersonalizedInsightsInputSchema,
    outputSchema: PersonalizedInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
